project:
  type: website

website:
  page-navigation: true
  title: "Met Zotero leren werken"
  site-url: "...."
  repo-url: https://github.com/RonaldVisser/Zotero_WC
  repo-actions: [issue]

  page-footer:
    right: "This page is built with [Quarto](https://quarto.org/)."
    left: "&copy; CC-By Ronald Visser, 2023"

  sidebar:
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/RonaldVisser/Zotero_WC
        text: "Github repository van deze website"
      - icon: mastodon
        href: https://akademienl.social/@RonaldVisser
        text: "Mastodon"

    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Welkom
      - href: install.qmd
        text: Installatie
      - href: zotero_start.qmd
        text: De eerste stappen
      - href: zotero_add.qmd
        text: Gegevens invoegen/opslaan
      - href: zotero_references.qmd
        text: Bronvermeldingen en literatuurlijst
      - href: zotero_organize_library.qmd
        text: Organiseren van jouw bibliotheek in Zotero
      - href: zotero_research_tool.qmd
        text: Onderzoek met Zotero
      - href: zotero_online.qmd
        text: Online werken met Zotero
      - href: about.qmd
        text: Over deze website




format:
  html:
    theme:
      light: [theme]
    code-copy: true
    code-overflow: wrap
    toc: true


filters:
  - quarto

